### ISSUE TITLE
Missaligned skeleton textures?

### ISSUE THREAD

**Issue by ProducerMZ** [Xires87/MobVariants#3]
Thank you for this mod, that in my opinion, brings some much needed variety to standard mobs.
All your mobs act and look perfect for me, except for these unfortunate three: the Soul Stealer, the Undead Warrior, and especially, the messed up Corsair. 
I can only presume that this is because they are all based on the skeleton model, and that perhaps another mod I have is corrupting them somehow, causing your skins to be misaligned.
My question is this;  is there anything I can do on my end to manually readjust your skins to fit again? ( ...Is that even a thing? lol )
I'd love to make this work somehow, as it is literally the only issue left after problem solving compatibility with over 400 mods for the past few weeks, and it would be so satisfying to say it all works! I am using Fabric version 4.3.2+1.20  .
Any help would be appreciated.  - Mike

![2023-12-26_21 45 48](https://github.com/Xires87/MobVariants/assets/123271596/82f6cde1-5991-4ce6-beb8-37eab8041611)

**Comment by Xires87** [comment]
Hello!
These mobs actually **use** skeleton model, so if any mod makes changes to the model, my mobs will change too.

You can modify textures to match the modified model, but I'm actually not 100% sure my predictions are correct, so please, find mod/mods causing this, so I can better investigate the problem.

**Comment by ProducerMZ** [comment]
Thanks for the response! 
I'm fairly certain what is causing the issue is a resource pack I'm using called, "AL's Skeletons Revamped". 

![pack](https://github.com/Xires87/MobVariants/assets/123271596/56259db2-76dd-4e81-b78c-3d88df81813c)

I'm using version 1.4 of that pack.
