### ISSUE TITLE
Directory renamed (loot_table)

### ISSUE THREAD

**Issue by ImWhiff** [Xires87/MobVariants#4]
Thanks for updating the mod to 1.21! I absolutely love this mod. I assume that you could be already aware of this, but just in case:

There is an error in the data folder. The loot_tables directory got renamed to loot_table in 1.21. In addition, looting_enchant & random_chance_with_looting was renamed in the functions field within the loot_table to enchanted_count_increase & random_chance_with_enchanted_bonus, respectively. For example: 
Old file for armored_spider:
[armored_spider.json](https://github.com/user-attachments/files/16519079/armored_spider.json)

Revised file:
[armored_spider.json](https://github.com/user-attachments/files/16519090/armored_spider.json)

Old file for frozen_zombie:
[frozen_zombie.json](https://github.com/user-attachments/files/16519135/frozen_zombie.json)

Revised file:
[frozen_zombie.json](https://github.com/user-attachments/files/16519153/frozen_zombie.json)

I might've missed other things. Anyways, keep up the great work 😼

**Comment by Xires87** [comment]
Fixed. Thanks for reporting, I completely forgot about loot tables.
