### ISSUE TITLE
Modrinth

### ISSUE THREAD

**Issue by calliecameron** [Xires87/MobVariants#5]
It would be convenient if the mod was on modrinth as well as curseforge - could you add it there?

**Comment by Xires87** [comment]
I might do it after porting the rest of my mods to 1.21

**Comment by Xires87** [comment]
https://modrinth.com/mod/fryc-mob-variants

**Comment by calliecameron** [comment]
Can you add the 1.19.2 versions there as well?

**Comment by Xires87** [comment]
Sorry, I won't do it. I don't want 1.19 versions to be on Modrinth, because they are outdated.
